#include "Menu.h"
#include "Location.h"
#include "LocationFileHandler.h"
#include "LocationManager.h"
#include "SearchWeatherData.h"
#include "ApiRequestHandler.h"
#include "Util.h"
#include <string>
#include <iostream>
#include <sstream>
#include <unordered_map>
#include <vector>
#include <iomanip>